apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-spring-app
  template:
    metadata:
      labels:
        app: basic-spring-app
    spec:
      containers:
      - name: basic-spring-app
        image: springacr1705.azurecr.io/basic-spring-app:${{ github.sha }}
        ports:
        - containerPort: 8080
---        
apiVersion: v1
kind: Service
metadata:
  name: basic-spring-app
spec:
  type: LoadBalancer
  ports:
  - port: 90
    protocol: TCP
    targetPort: 8080
  selector:
    app: basic-spring-app
