name: Java CI with Maven

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: springacr1705.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build . -t springacr1705.azurecr.io/basic-spring-app:${{ github.sha }}
        docker push springacr1705.azurecr.io/basic-spring-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      run: |
        az aks get-credentials --resource-group actions --name actions --overwrite-existing
    - name: Delete existing ACR Pull Secret
      run: |
        kubectl delete secret acr-secret || echo "Secret not found, continuing..."
    - name: Create ACR Pull Secret in AKS
      run: |
        kubectl create secret docker-registry acr-secret \
          --docker-server=springacr1705.azurecr.io \
          --docker-username=${{ secrets.ACR_USERNAME }} \
          --docker-password=${{ secrets.ACR_PASSWORD }} \
          --docker-email=Sneha.Vijapur@valtech.com

    - name: List files in the repository (for debugging)
      run: ls -R
    - name: Deploy to AKS
      uses: azure/k8s-deploy@v5
      with:
        manifests: |
          Github_actions_demo/deployment.yaml
        images: |
          springacr1705.azurecr.io/basic-spring-app:${{ github.sha }}
        imagepullsecrets: |
          acr-secret

    # - name: Build and Push Docker Image
    #   uses: mr-smithers-excellent/docker-build-push@v4
    #   with:
    #     image: smayav/actions_demo
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Pull Docker Image
    #   run: |
    #      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #      docker pull smayav/actions_demo:main-a9abb7b
